### ISSUE TITLE
Change the name of 'Roadmap'

### ISSUE THREAD

**Issue by kaosdev** [kaosdev/map.js#2]
Roadmap is not a good name.
A better name could be just Map, but it's a standard js class.

Find a better name and replace it everywhere.

**Comment by abheepsapattnaik** [comment]
Hey @kaosdev 
Is it fine to replace the RoadMap to something like MapRepresentation or SketchMap?

Let me know if I can go ahead with applying this change

**Comment by kaosdev** [comment]
I really like SketchMap. You can go ahead.
The change should be simple, a replace all should be fine.

Just make sure to change the names also in the README.MD and in the example.

For any question let me know here.

Thank you!

**Comment by abheepsapattnaik** [comment]
Sure. I will go ahead with SketchMap.

So are we planning to change the css class names too? I see there are several css class and constants with roadmap name.

**Comment by kaosdev** [comment]
Yeah we should change them also, but that's not important to do now.

In the next future I'm planning to change the style structure completely (to make theming easier), so we can rename the classes in another PR.

**Comment by abheepsapattnaik** [comment]
Okay cool :)
