### ISSUE TITLE
Wrong dependency in package.json

### ISSUE THREAD

**Issue by kaosdev** [kaosdev/map.js#6]
Currently `rollup-plugin-istanbul` is listed as a dependency in the package.json.

This is wrong and it should be a dev dependency.

**Comment by abheepsapattnaik** [comment]
I have raised a pull request for the same
[Refactor dependency pull request](https://github.com/kaosdev/map.js/pull/7)

Could you please review it

**Comment by kaosdev** [comment]
> I have raised a pull request for the same
> [Refactor dependency pull request](https://github.com/kaosdev/map.js/pull/7)
> 
> Could you please review it
> 

Thank you for the PR. I'm sorry for the late reply.
I hope to find some more time for this repo in the near future.

**Comment by abheepsapattnaik** [comment]
No worries. Thank you
